# Build native binaries on Linux, Windows, macOS.
# Copy to .github/workflows/build.yml
name: Build for all platforms
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: azolfagharj/action-caddy-builder@v1
        id: build
        with:
          caddy-version: v2.10.2
          modules: github.com/caddy-dns/cloudflare
      - uses: actions/upload-artifact@v4
        with:
          name: caddy-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ steps.build.outputs.caddy-path }}
