# Build to custom output directory.
# Copy to .github/workflows/build.yml
name: Build to dist
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azolfagharj/action-caddy-builder@v1
        id: build
        with:
          caddy-version: v2.10.2
          output-dir: ./dist
          modules: github.com/caddy-dns/cloudflare
      - run: ls -la ./dist/
