# Build all platforms + Linux arm64, attach to release.
# Copy to .github/workflows/release.yml
# Trigger: push tag v*
name: Release (full matrix)
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-22.04-arm
            goos: linux
            goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: macos-15-intel
            goos: darwin
            goarch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: azolfagharj/action-caddy-builder@v1
        id: build
        with:
          caddy-version: v2.10.2
          modules: github.com/caddy-dns/cloudflare
      - uses: actions/upload-artifact@v4
        with:
          name: caddy-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ steps.build.outputs.caddy-path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            caddy-linux-amd64/*
            caddy-linux-arm64/*
            caddy-windows-amd64/*
            caddy-darwin-arm64/*
            caddy-darwin-amd64/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
